//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci
    {
        public Klienci()
        {
            this.Mandaties = new HashSet<Mandaty>();
            this.Zakupione_bilety = new HashSet<Zakupione_bilety>();
        }
    
        public int Id_Klienta { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public decimal Saldo { get; set; }
        public string Token { get; set; }
        public string Login { get; set; }
        public string Haslo { get; set; }
    
        public virtual ICollection<Mandaty> Mandaties { get; set; }
        public virtual ICollection<Zakupione_bilety> Zakupione_bilety { get; set; }
    }
}
