//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rodzaje_biletów
    {
        public Rodzaje_biletów()
        {
            this.Zakupione_bilety = new HashSet<Zakupione_bilety>();
        }
    
        public int Id_Rodzaju { get; set; }
        public string Nazwa { get; set; }
        public decimal Cena { get; set; }
        public Nullable<System.DateTime> Czas_trwania { get; set; }
    
        public virtual ICollection<Zakupione_bilety> Zakupione_bilety { get; set; }
    }
}
