//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakupione_bilety
    {
        public int Id_Biletu { get; set; }
        public int Id_Rodzaju { get; set; }
        public int Id_Klienta { get; set; }
        public System.DateTime Ważność_OD { get; set; }
        public System.DateTime Ważność_DO { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Rodzaje_biletów Rodzaje_biletów { get; set; }
    }
}
