//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrolerzy
    {
        public Kontrolerzy()
        {
            this.Mandaties = new HashSet<Mandaty>();
        }
    
        public int Id_Kontrolera { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public System.DateTime Umowa_OD { get; set; }
        public System.DateTime Umowa_DO { get; set; }
        public string Token { get; set; }
        public string Login { get; set; }
        public string Haslo { get; set; }
    
        public virtual ICollection<Mandaty> Mandaties { get; set; }
    }
}
