//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9CA667_projektPZEntities : DbContext
    {
        public DB_9CA667_projektPZEntities()
            : base("name=DB_9CA667_projektPZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Klienci> Kliencis { get; set; }
        public DbSet<Kontrolerzy> Kontrolerzies { get; set; }
        public DbSet<Mandaty> Mandaties { get; set; }
        public DbSet<Rodzaje_biletów> Rodzaje_biletów { get; set; }
        public DbSet<Zakupione_bilety> Zakupione_bilety { get; set; }
    }
}
